services:
  - type: web
    name: umrah-plus-travel
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /static/*
        destination: /static/:splat
      - type: rewrite
        source: /assets/*
        destination: /assets/:splat
      - type: rewrite
        source: /*
        destination: /index.html
